plugin: amazon.aws.aws_ec2
boto_profile: default
strict: True
regions:
  - eu-west-1
keyed_groups:
  - key: tags
    prefix: tag
hostnames:
  - ip-address
  - private-ip-address
compose:
  ansible_host: private_ip_address